wandb_version: 1

gwnce.cut_rate:
  value: 0.1336022714766672
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.0019030851726829995
loss.contrastive.name:
  value: gwnce
model.name:
  value: GIN
