wandb_version: 1

gwnce.cut_rate:
  value: 0.1483662503715859
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 4.081735988095408e-05
loss.contrastive.name:
  value: gwnce
model.name:
  value: GAT
