wandb_version: 1

gwnce.cut_rate:
  value: 0.1773574300660315
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 4.0603149869383285e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
