wandb_version: 1

gwnce.cut_rate:
  value: 0.10810017544455204
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.00029909268188482377
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
