wandb_version: 1

gwnce.cut_rate:
  value: 0.2719667812723803
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.003928143758349941
loss.contrastive.name:
  value: gwnce
model.name:
  value: GIN
