wandb_version: 1

gwnce.cut_rate:
  value: 0.3406345852944727
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.0005959626240267769
loss.contrastive.name:
  value: infonce
model.name:
  value: GAT
