wandb_version: 1

gwnce.cut_rate:
  value: 0.11526986106653564
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.0011658214128252358
loss.contrastive.name:
  value: gwnce
model.name:
  value: GAT
