wandb_version: 1

gwnce.cut_rate:
  value: 0.11310896062606052
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 1.000210296762028e-05
loss.contrastive.name:
  value: gwnce
model.name:
  value: GCN
