wandb_version: 1

gwnce.cut_rate:
  value: 0.09353262728044714
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.0028863849296682487
loss.contrastive.name:
  value: gwnce
model.name:
  value: GAT
