wandb_version: 1

gwnce.cut_rate:
  value: 0.13480962061869495
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.00015366501442681227
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
