wandb_version: 1

gwnce.cut_rate:
  value: 0.30740183643917957
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.00019524226910080987
loss.contrastive.name:
  value: gwnce
model.name:
  value: GAT
