wandb_version: 1

gwnce.cut_rate:
  value: 0.3247144612437568
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 3.963848609328257e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
