wandb_version: 1

gwnce.cut_rate:
  value: 0.35814374713599173
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.004561421038895714
loss.contrastive.name:
  value: infonce
model.name:
  value: GAT
