wandb_version: 1

gwnce.cut_rate:
  value: 0.341542091161586
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.0018101047872603644
loss.contrastive.name:
  value: gwnce
model.name:
  value: GCN
