wandb_version: 1

gwnce.cut_rate:
  value: 0.011464542683229884
hparams.train.batch_size:
  value: 32
hparams.train.learning_rate:
  value: 0.0002035409922250982
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
