wandb_version: 1

gwnce.cut_rate:
  value: 0.3617010462342423
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 1.5031156766431026e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GAT
