wandb_version: 1

gwnce.cut_rate:
  value: 0.35012394340467656
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 3.608343400465724e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
