wandb_version: 1

gwnce.cut_rate:
  value: 0.4065979904400428
hparams.train.batch_size:
  value: 32
hparams.train.learning_rate:
  value: 9.693186305839432e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GAT
