wandb_version: 1

gwnce.cut_rate:
  value: 0.11363952912003172
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.00010512355628953224
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
