wandb_version: 1

gwnce.cut_rate:
  value: 0.4210393154697278
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.00046646239663177913
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
