wandb_version: 1

gwnce.cut_rate:
  value: 0.3926774227510299
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.0021405613048234703
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
