wandb_version: 1

gwnce.cut_rate:
  value: 0.0912025415416594
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.007447417291400213
loss.contrastive.name:
  value: gwnce
model.name:
  value: GAT
