wandb_version: 1

gwnce.cut_rate:
  value: 0.14360167518500244
hparams.train.batch_size:
  value: 32
hparams.train.learning_rate:
  value: 0.0005817151583309634
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
