wandb_version: 1

gwnce.cut_rate:
  value: 0.3170133115351396
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.001645214111108358
loss.contrastive.name:
  value: infonce
model.name:
  value: GAT
