wandb_version: 1

gwnce.cut_rate:
  value: 0.1392627818953075
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.00017944150247826057
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
