wandb_version: 1

gwnce.cut_rate:
  value: 0.35605073282050503
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.004065866669754119
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
