wandb_version: 1

gwnce.cut_rate:
  value: 0.0003596932034157785
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.004373200314058676
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
