wandb_version: 1

gwnce.cut_rate:
  value: 0.3052735680481352
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 7.742650902819045e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
