wandb_version: 1

gwnce.cut_rate:
  value: 0.3623687678806913
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.0022254007678685554
loss.contrastive.name:
  value: gwnce
model.name:
  value: GIN
