wandb_version: 1

gwnce.cut_rate:
  value: 0.16355368559183942
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 1.2343888833302792e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
