wandb_version: 1

gwnce.cut_rate:
  value: 0.2071431232854475
hparams.train.batch_size:
  value: 32
hparams.train.learning_rate:
  value: 0.00016634762519160496
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
