wandb_version: 1

gwnce.cut_rate:
  value: 0.31677422918371895
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.006940468096885215
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
