wandb_version: 1

gwnce.cut_rate:
  value: 0.08834494180819624
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.00586718317582322
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
