wandb_version: 1

gwnce.cut_rate:
  value: 0.0781757883490326
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.0002988788289094761
loss.contrastive.name:
  value: gwnce
model.name:
  value: GIN
