wandb_version: 1

gwnce.cut_rate:
  value: 0.08918716292129175
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.0009044927291817564
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
