wandb_version: 1

gwnce.cut_rate:
  value: 0.2557304102498285
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 1.0902964792791709e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
