wandb_version: 1

gwnce.cut_rate:
  value: 0.08117424817044577
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 4.97744338010965e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GAT
