wandb_version: 1

gwnce.cut_rate:
  value: 0.13228235549996809
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.0003000051701476309
loss.contrastive.name:
  value: gwnce
model.name:
  value: GAT
