wandb_version: 1

gwnce.cut_rate:
  value: 0.3132109443149115
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 1.0473871332892151e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
