wandb_version: 1

gwnce.cut_rate:
  value: 0.06360004922927043
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 3.437433396122426e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
