wandb_version: 1

gwnce.cut_rate:
  value: 0.008403211424887425
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.004065006218919627
loss.contrastive.name:
  value: gwnce
model.name:
  value: GAT
