wandb_version: 1

gwnce.cut_rate:
  value: 0.38217708256986954
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.0009793648075735065
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
