wandb_version: 1

gwnce.cut_rate:
  value: 0.1669926561879409
hparams.train.batch_size:
  value: 32
hparams.train.learning_rate:
  value: 0.00011960560617952856
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
