wandb_version: 1

gwnce.cut_rate:
  value: 0.08096351314338784
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.006228570794957667
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
