wandb_version: 1

gwnce.cut_rate:
  value: 0.2917807867121946
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.0002441682114790997
loss.contrastive.name:
  value: gwnce
model.name:
  value: GAT
