wandb_version: 1

gwnce.cut_rate:
  value: 0.28391103596004014
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 9.430042441367866e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
