wandb_version: 1

gwnce.cut_rate:
  value: 0.23292596648351432
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.006426899717944619
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
