wandb_version: 1

gwnce.cut_rate:
  value: 0.37789940724459525
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.0018803018388878472
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
