wandb_version: 1

gwnce.cut_rate:
  value: 0.10387667327578116
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.00018398688082527735
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
