wandb_version: 1

gwnce.cut_rate:
  value: 0.2914784714269764
hparams.train.batch_size:
  value: 32
hparams.train.learning_rate:
  value: 0.0006294552443947642
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
