wandb_version: 1

gwnce.cut_rate:
  value: 0.11591494092906084
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.00012785969459912344
loss.contrastive.name:
  value: gwnce
model.name:
  value: GAT
