wandb_version: 1

gwnce.cut_rate:
  value: 0.4120051372813642
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.0012175837656627144
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
