wandb_version: 1

gwnce.cut_rate:
  value: 0.3897487078012219
hparams.train.batch_size:
  value: 32
hparams.train.learning_rate:
  value: 0.007567034379100975
loss.contrastive.name:
  value: gwnce
model.name:
  value: GIN
