wandb_version: 1

gwnce.cut_rate:
  value: 0.39066282987992434
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.004641721474119453
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
