wandb_version: 1

gwnce.cut_rate:
  value: 0.4852752804410895
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.001103723676887797
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
