wandb_version: 1

gwnce.cut_rate:
  value: 0.4578433674721192
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 6.615171189255529e-05
loss.contrastive.name:
  value: gwnce
model.name:
  value: GIN
