wandb_version: 1

gwnce.cut_rate:
  value: 0.3375096736960804
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 1.9363351350451575e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
