wandb_version: 1

gwnce.cut_rate:
  value: 0.28181012409203854
hparams.train.batch_size:
  value: 32
hparams.train.learning_rate:
  value: 1.8948004572956728e-05
loss.contrastive.name:
  value: gwnce
model.name:
  value: GIN
