wandb_version: 1

gwnce.cut_rate:
  value: 0.12538891449024123
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 7.701463031067264e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
