wandb_version: 1

gwnce.cut_rate:
  value: 0.33952799339666884
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.0015356388924976266
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
