wandb_version: 1

gwnce.cut_rate:
  value: 0.484034058953036
hparams.train.batch_size:
  value: 32
hparams.train.learning_rate:
  value: 0.0021198173891055485
loss.contrastive.name:
  value: gwnce
model.name:
  value: GAT
