wandb_version: 1

gwnce.cut_rate:
  value: 0.4337923436481362
hparams.train.batch_size:
  value: 32
hparams.train.learning_rate:
  value: 0.002278107531570088
loss.contrastive.name:
  value: gwnce
model.name:
  value: GIN
