# -------------------------------------------------------------------
# Core configuration.  Default mode is 'train'; override via +mode=dev or +mode=test
# -------------------------------------------------------------------
defaults:
  - _self_
  - mode: dev      # choices: train, dev, test
  - hparams: hparams
  - model:   model
  - loss:    loss
  - wandb:   wandb
  - callbacks: callbacks
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

# mode: train          # default; +mode=dev or +mode=test will load conf/mode/*.yaml
data_dir: ${hydra:runtime.cwd}/../../../data/asep/m3epi
results_dir: ${hydra:runtime.cwd}/../../../results/hgraphepi/m3epi
try_gpu: true
logging_method: wandb
keep_interim_ckpts: true
num_threads: 4
seed: 42

# -------------------------------------------------------
# For visualize_embeddings.py
# -------------------------------------------------------
visualize:
  checkpoint: ${hydra:runtime.cwd}/../../../results/hgraphepi/m3epi/checkpoints/model-02-7.17.pt
  batch_size: 32
  out_dir:    ${hydra:runtime.cwd}/../../../results/hgraphepi/m3epi/figures

# to disable hydra to save configs, overrides, and log files to `outputs` dir
hydra:  
  output_subdir: null  
  run:  
    dir: .



# defaults:
#   - _self_
#   - mode: dev # choices: train, dev ## populates dev/train yaml files
#   - hparams: hparams
#   - model: model
#   - loss: loss
#   - wandb: wandb
#   - callbacks: callbacks

# data_dir: ${hydra:runtime.cwd}/../../../data/asep/m3epi
# results_dir: ${hydra:runtime.cwd}/../../../results/hgraphepi/m3epi
# try_gpu: true 
# logging_method: wandb
# keep_interim_ckpts: true
# num_threads: 4
# seed: 42


# # new section for visualization defaults
# visualize:
#   # relative to project root
#   checkpoint: ${hydra:runtime.cwd}/../../../results/hgraphepi/m3epi/checkpoints/model-02-7.17.pt
#   batch_size: 32
#   out_dir:    ${hydra:runtime.cwd}/../../../results/hgraphepi/m3epi/figures      # save tsne_*.png here





# modifying mode/train.yaml will not effect experiments
# instead modify conf/*.yaml for train/dev
# run sweep.py to execute sweep.yaml for sweep in train mode




# work_dir: ${hydra:runtime.cwd}

# defaults:
#   - hydra: hydra
#   - hparams: hparams
#   - loss: loss
#   - optimizer: adam
#   - callbacks: callbacks
#   - wandb_init: wandb
#   - _self_ # this is needed for hydra to recognize the config group
#   - pretrained_model: null

# mode: "train"  # in {dev, sweep, train, tuning}
# try_gpu: true
# logging_method: wandb  # choices: wandb (default), tensorboard
# keep_interim_ckpts: true  # keep all interim checkpoints
# num_threads: 4
# seed: ???