wandb_version: 1

gwnce.cut_rate:
  value: 0.281047358101928
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 3.593291803131924e-05
loss.contrastive.name:
  value: gwnce
model.name:
  value: GAT
