wandb_version: 1

gwnce.cut_rate:
  value: 0.3109159276364209
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 1.9022930709837594e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
