wandb_version: 1

gwnce.cut_rate:
  value: 0.020451695954963656
hparams.train.batch_size:
  value: 32
hparams.train.learning_rate:
  value: 2.971449547856456e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
