wandb_version: 1

gwnce.cut_rate:
  value: 0.4213781481733852
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.0012703216432400864
loss.contrastive.name:
  value: gwnce
model.name:
  value: GCN
