wandb_version: 1

gwnce.cut_rate:
  value: 0.49794778049965505
hparams.train.batch_size:
  value: 32
hparams.train.learning_rate:
  value: 0.0012439054134745135
loss.contrastive.name:
  value: gwnce
model.name:
  value: GIN
