wandb_version: 1

gwnce.cut_rate:
  value: 0.3705748959920333
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 1.5257059650809243e-05
loss.contrastive.name:
  value: gwnce
model.name:
  value: GCN
