wandb_version: 1

gwnce.cut_rate:
  value: 0.3775162414284896
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 2.967708035599424e-05
loss.contrastive.name:
  value: gwnce
model.name:
  value: GIN
