wandb_version: 1

gwnce.cut_rate:
  value: 0.12359782894236226
hparams.train.batch_size:
  value: 32
hparams.train.learning_rate:
  value: 1.996160030674924e-05
loss.contrastive.name:
  value: gwnce
model.name:
  value: GIN
