wandb_version: 1

gwnce.cut_rate:
  value: 0.4930201827777646
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.009462167821122589
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
