wandb_version: 1

gwnce.cut_rate:
  value: 0.4048738106858748
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.0009449927737278712
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
