wandb_version: 1

gwnce.cut_rate:
  value: 0.16845413020985173
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 2.0190633137445017e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GAT
