wandb_version: 1

gwnce.cut_rate:
  value: 0.1807795206349181
hparams.train.batch_size:
  value: 32
hparams.train.learning_rate:
  value: 0.0005308436185317275
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
