wandb_version: 1

gwnce.cut_rate:
  value: 0.09642522761523388
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.0008424782357794256
loss.contrastive.name:
  value: infonce
model.name:
  value: GAT
