wandb_version: 1

gwnce.cut_rate:
  value: 0.3804548132546361
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 1.9717648372710997e-05
loss.contrastive.name:
  value: gwnce
model.name:
  value: GIN
