wandb_version: 1

gwnce.cut_rate:
  value: 0.4534733516467385
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.003010140434298528
loss.contrastive.name:
  value: gwnce
model.name:
  value: GCN
