wandb_version: 1

gwnce.cut_rate:
  value: 0.09862581870610744
hparams.train.batch_size:
  value: 32
hparams.train.learning_rate:
  value: 0.0007529853657774397
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
