wandb_version: 1

gwnce.cut_rate:
  value: 0.08149153555248051
hparams.train.batch_size:
  value: 64
hparams.train.learning_rate:
  value: 0.0030123669120295966
loss.contrastive.name:
  value: infonce
model.name:
  value: GIN
