wandb_version: 1

gwnce.cut_rate:
  value: 0.04779895840584758
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 0.0003057904351626002
loss.contrastive.name:
  value: gwnce
model.name:
  value: GCN
