wandb_version: 1

gwnce.cut_rate:
  value: 0.18701578776839103
hparams.train.batch_size:
  value: 128
hparams.train.learning_rate:
  value: 1.2148004471096295e-05
loss.contrastive.name:
  value: infonce
model.name:
  value: GCN
